### ISSUE TITLE
Blank space in all my code blocks

### ISSUE THREAD

**Issue by brettcurtis** [hibbitts-design/grav-theme-learn2-git-sync#12]
If I create a multiple line code blocks I see a blank space on the first line. I can't figure out why and it's driving me crazy :)  Any thoughts? 

For example all my code looks like this:

```none
 blaa -blaa -blaa
Testing 123 test test
```
NOTE: I'm intentionally putting a space in here to describe what I'm seeing.

**Comment by paulhibbitts** [comment]
Thanks for reporting the issue, can you please test the same with the Learn2 theme?

**Comment by brettcurtis** [comment]
Ahh yeah it's in the learn2 theme.

**Comment by paulhibbitts** [comment]
Likely not much I can do, however if you could please share an example page with this issue I am happy to take a look.

**Comment by brettcurtis** [comment]
Shoot, the site is not public facing otherwise I would. Maybe it's best if I report it as an issue on the learn2 repo and see if they can help. 

Sorta OT but if I want to use prism highlighter plugin instead of highlighter is it simple to remove the clippy icon from code blocks? If it's not a trivial thing I'll go do some research to figure out how. I am using my own child theme based off yours and learn2. I'm not a web design guy at all.. 

Feel free to close, and thanks offering the help!

**Comment by paulhibbitts** [comment]
Yes, it might be best to report the issue on the Learn2 repo.

You might be able to hide the Clippy icon via CSS? Just a guess but that is what I would try.

If you could make a sample page with "fake" content I'd still be happy to take a look🙂

**Comment by brettcurtis** [comment]
ok I was able to add the following to my custom.css:
```css
.copy-to-clipboard {
  background-image: none;
```
Let me see if it's tough to spin up a test grav site and expose it quickly.
