### ISSUE TITLE
Multisite compatibility

### ISSUE THREAD

**Issue by tituspijean** [hibbitts-design/grav-theme-learn2-git-sync#14]
Hi,

This is a followup of #13. I think I delved too far in the rabbit hole. :)
There are other instances of code that prevent full compatibility with multisites.

For example in `templates/partials/github_link.html.twig`:
```twig
{% set git_repo_edit_link_url = git_repo_link_url ~  ('/'~page.filePathClean)|replace({'/user/':'/'}) %}
```
would output:
`https://github.com/REPO/blob/master/sites/SUBSITE/pages/01.install/docs.md`
while the correct link would have been:
`https://github.com/REPO/blob/master/pages/01.install/docs.md`

I am not fluent enough in Twig, so I hacked the code like this for my own convenience:
```twig
{% set git_repo_edit_link_url = git_sync_repo_link ~ 'blob/master' ~ ('/pages'~('/'~page.filePathClean)|split('/pages').1) %}
```
I guess there are smarter ways to do so, maybe by relying on `local_repository` key in the config or retrieving the actual `user://` path for the subsite and removing it from `page.filePathClean`?

**Comment by paulhibbitts** [comment]
Thanks for reporting the issue @tituspijean , however for this one I think the best approach is for you to adjust the Twig file on your end (in an inherited theme I assume). I've gone through a fair number of iterations on the Twig to support multiple hosting situations and I am wary of making any further changes at this point. Perhaps sometime in the future I may be able to explore this issue further.
