### ISSUE TITLE
Nested collapsible menus in the left sidebar

### ISSUE THREAD

**Issue by AEW2015** [hibbitts-design/grav-theme-learn2-git-sync#15]
How do you edit the theme css file to allow for nested collapsible menus in the left sidebar?

Thanks

**Comment by paulhibbitts** [comment]
Hi @AEW2015 , I do not think that that's support with the parent theme (Learn2). My CSS skills are very limited🙂 You might try searching the Learn2 repo (https://github.com/getgrav/grav-theme-learn2) if any others have tried a similar thing?
