### ISSUE TITLE
"Edit this Page" under multisite incorrect

### ISSUE THREAD

**Issue by logixworx** [hibbitts-design/grav-theme-learn2-git-sync#17]
I followed this issue report to get Learn2 GitSync working  in a multi-site format, where Learn2 GitSync is a subdomain that commits to github.

https://github.com/trilbymedia/grav-plugin-git-sync/issues/173

The only issue that remains is the "Edit this Page" link in the upper-right corner needs to reflect this.

How do I fix this?  Thanks.

**Comment by paulhibbitts** [comment]
Hi @logixworx , sorry but right now Grav multisite is not supported in Learn2 with Git Sync. One alternative is to try Learn2 and manually config the site.yaml file to the content repository etc.

If you do the above, please let me know if it works with multisite, thanks!

**Comment by logixworx** [comment]
I've got it working though -  i just need "Edit this Page" to go to the correct link when clicked.  I narrowed it down to github_link.html.twig and tried to understand how it culls env/subdomain.name  from the link but havent had any luck.

**Comment by paulhibbitts** [comment]
Thanks for the update @logixworx , while the Twig I am sure can be further improved it is basically a calc from the root of the Git repo along with the current page path etc. Like I said, none of it was designed to support multisite but let me know if you find a solution.

**Comment by logixworx** [comment]
check it out:

logixworx.com//8080
sitea.logixworx.com/8080
siteb.logixworx.com/8080

I tested updates to and from github both directions as seen on this page - worked fine:

https://github.com/logixworx/learn2a/blob/master/env/sitea.logixworx.com/pages/01.basics/chapter.md  

so you're saying its not trivially easy to change the "Edit my Page" link  in the upper right corner  from

https://github.com/logixworx/learn2a/blob/master/env/sitea.logixworx.com/pages/01.basics/chapter.md   

to:

https://github.com/logixworx/learn2a/blob/master/pages/01.basics/chapter.md

?

?

**Comment by logixworx** [comment]
sorry, I updated the above comment.. the links werent correct

**Comment by logixworx** [comment]
hmm now my edits to github_link.html.twig  are showing up... odd.
