### ISSUE TITLE
Enhancement Question

### ISSUE THREAD

**Issue by stoosepp** [hibbitts-design/grav-theme-learn2-git-sync#18]
This theme is near perfect for what I want to use it for - open textbook. Have been looking at Jupiter books, and I love following features:

- the ability to collapse the sidebar
- have subsections of a single page (probably headers) as a right sidebar
- PDF and epub export 

Has this been discussed for Learn2 yet?

New to grav themes but would love to help out!

**Comment by paulhibbitts** [comment]
Hi @stoosepp , thanks for your interest in this theme!

The first two items would require changes related to the base theme (Learn2) which while maintained in no longer under active development (the Grav Team is now using an unreleased version of Learn4 for their own docs). While of course possible I tend to avoid changes in my inherited theme that would affect base-theme behavior etc. The last item (PDF) could be approached as a Plugin, but would likely be quite involved.

I am sure you are also looking at other approaches too - I wonder if a Markdown docs tool such as Docsify (which does not require the use of custom frontmatter in MD files as Grav does) which has both of your first two items + PanDoc might be another alternative to explore?

Also, have you seen the Scholar Theme? https://github.com/OleVik/grav-theme-scholar It is a standalone theme (vs. inherited like mine) and Ole is an amazing developer :-) You might want to run by your items of interest with him if Scholar looks like a good candidate too etc.

**Comment by paulhibbitts** [comment]
I will close this issue for now @stoosepp . Please feel free to follow-up with me if I can be of help with either Grav, Docsify, or Markdown publishing tools in general!

**Comment by stoosepp** [comment]
Awesome. Thanks @paulhibbitts
