### ISSUE TITLE
Built with Grav link is not displayed correctly

### ISSUE THREAD

**Issue by timinator2020** [hibbitts-design/grav-theme-learn2-git-sync#19]
The text displayed on the bottom of the sidebar is as follows:
`Built with <a href="http://getgrav.org">Grav</a> - The Modern Flat File CMS`

There is no clickable link, it is displaying the text literally.

If I edit templates/partials/sidebar.html.twig and add **|raw** to the variable expansion, it works:
`<p>{{ 'THEME_LEARN2_BUILT_WITH_GRAV'|t|raw }}</p>`

That displays a clickable link:
Built with [Grav](http://getgrav.org/) - The Modern Flat File CMS

I suspect that's a bug, but it's also very possible I have something else configured wrong, thus requiring the use of raw?

Thanks for checking.

**Comment by paulhibbitts** [comment]
Hi @timinator2020 , thanks for reporting the issue. It looks like that was missed when the theme was updated for Grav 1.7+, I'll take a look and will post an update in the next few days.

**Comment by paulhibbitts** [comment]
I've just made a new release of Learn2 with Git Sync theme @timinator2020 , could you please update your installation and test? Thanks, Paul.

**Comment by timinator2020** [comment]
Yup, that took care of it. Thanks.

**Comment by paulhibbitts** [comment]
Great, thanks for testing and reporting the issue.
