### ISSUE TITLE
Slash is not added at the end of a custom git repository url for the "Edit this page" link

### ISSUE THREAD

**Issue by amiram** [hibbitts-design/grav-theme-learn2-git-sync#2]
Steps to reproduce:

Set the git remote url to "others" with the repo url without a slash at the end.
e.g. http://tfs-host.com/tfs/MyCollection/MyProject/_git/wiki

Open a page and click on the "Edit this Page" link.

Expected result:
Link should be http://tfs-host.com/tfs/MyCollection/MyProject/_git/wiki/blob/master/pages

Actual Result:
Link is http://tfs-host.com/tfs/MyCollection/MyProject/_git/wikiblob/master/pages

Workaround:
Add a slash in the repo url
http://tfs-host.com/tfs/MyCollection/MyProject/_git/wiki/

BTW, it is not happening with github.

**Comment by paulhibbitts** [comment]
Thanks for your PR @amiram , I've tested it with GitHub, GitLab and Bitbucket and everything looks good!

**Comment by amiram** [comment]
BTW, I've seen a new release in this repo, but the skeleton is in this repo https://github.com/hibbitts-design/grav-skeleton-learn2-with-git-sync. Is it supposed to be updated?
