### ISSUE TITLE
skeleton don't have **user/themes/learn2-git-sync/images/clippy.svg**

### ISSUE THREAD

**Issue by hhk7734** [hibbitts-design/grav-theme-learn2-git-sync#9]
skeleton don't have **user/themes/learn2-git-sync/images/clippy.svg**

**Comment by paulhibbitts** [comment]
Thanks for reporting this @hhk7734 ! I was assuming these would be inherited from the parent theme (Learn2) but it looks like they were not. I've now released an update to the theme with the same items in the `images` folder as `Learn2`. https://github.com/hibbitts-design/grav-theme-learn2-git-sync/releases/tag/v1.5.2
